Repository Gretskie-Oreshki/online-testing-tool, pull requests merged in 2025-03, with the labels that each got.

#7 Added About page and edit .gitignore
  .gitignore
  app/src/main/java/org/example/AboutPageController.java
  app/src/main/java/org/example/AccountController.java
  app/src/main/resources/templates/about.html
  app/src/main/resources/templates/index.html
Labels: enhancement, backend

#20 sqlite db
  .gitignore
  app/build.gradle
  app/src/main/java/org/example/controllers/ExampleDBController.java
  app/src/main/java/org/example/model/Guest.java
  app/src/main/java/org/example/model/Result.java
  app/src/main/java/org/example/model/TestEntity.java
  app/src/main/java/org/example/repository/GuestRepository.java
  app/src/main/java/org/example/repository/ResultRepository.java
  app/src/main/java/org/example/repository/TestRepository.java
  app/src/main/resources/application.properties
Labels: backend

#29 [feat] Add password generation for Guest
  app/src/main/java/org/testingTool/model/Guest.java
  app/src/main/java/org/testingTool/model/GuestEntity.java
  app/src/main/java/org/testingTool/model/ResultEntity.java
  app/src/main/java/org/testingTool/repository/GuestRepository.java
  app/src/main/java/org/testingTool/repository/ResultRepository.java
Labels: enhancement, backend

#30 [chore] Delete unnecessary controllers
  app/src/main/java/org/testingTool/controllers/AboutPageController.java
  app/src/main/java/org/testingTool/controllers/AccountController.java
  app/src/main/java/org/testingTool/controllers/ContactPageController.java
  app/src/main/java/org/testingTool/controllers/ExampleDBController.java
Labels: backend

#24 [feat] Add Admin Page
  app/.classpath
  app/bin/main/org/example/AccountController.class
  app/bin/main/org/example/App.class
  app/bin/main/org/example/IndexController.class
  app/bin/main/org/example/LoginController.class
  app/bin/main/org/example/SecurityConfig.class
  app/src/main/java/org/testingTool/SecurityConfig.java
  app/src/main/java/org/testingTool/controllers/AdminController.java
  app/src/main/java/org/testingTool/model/AdminEntity.java
  app/src/main/java/org/testingTool/repository/AdminRepository.java
Labels: backend

#31 [chore] Delete unnecessary templates
  app/src/main/resources/templates/about.html
  app/src/main/resources/templates/account.html
  app/src/main/resources/templates/contact.html
Labels: frontend
